apiVersion: v1
appVersion: v0.3.2
description: A Helm chart for mysql operator
home: https://github.com/presslabs/mysql-operator
keywords:
- mysql
- percona
- orchestrator
- presslabs
name: mysql-operator
sources:
- https://github.com/presslabs/mysql-operator.git
version: 0.3.2
